version: '3'
services:
    kserver:
        build: ./dockerfiles/kserver
        hostname: "kserver"
        ports:
            - "8686:8686"
        environment:
            KSERVER_ENV: LOCAL_DEVELOPMENT
        stdin_open: true
        networks:
            - infranet
        volumes:
            - ./db:/db
        command: >
                bash  -c "\
                    rm -rf /var/lib/postgres/data/* && \
                    sudo -u postgres /usr/bin/initdb /var/lib/postgres/data/ && \
                    cp postgresql.conf /var/lib/postgres/data/postgresql.conf && \
                    sudo -u postgres /usr/bin/pg_ctl -D /var/lib/postgres/data/ start && \
                    db/./db_init.sh && \
                    psql kiq < db/kiq_platform.sql -U kiq_admin -w -h 0.0.0.0 && \
                    cd target && \
                    ./kserver --port=8686\
                "
    ky_gui:
        build: ./dockerfiles/ky_gui
        hostname: "ky_gui"
        environment:
            KY_GUI_ENV: LOCAL_DEVELOPMENT
        links:
            - "kserver"
        depends_on:
            - "kserver"
        stdin_open: true
        networks:
            - infranet
        command: >
                bash  -c "echo \"KY_GUI container has been built and prepared. To run on Linux, use this command: docker run --device /dev/dri/ -it --network host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix:0 kiq_platform_ky_gui ./target/ky_gui 127.0.0.1 8686 test\nTo run on Mac, follow the instructions posted here: https://github.com/StronglogicSolutions/kiq_demo/blob/master/README.md
                \""
networks:
    infranet:
